expansion: "BLB"

scraping:
  base_url: "https://aetherhub.com/Limited/Ratings/"

scryfall_api:
  base_url: "https://api.scryfall.com/cards/search/"
  query_template: "?order=set&q=e%3A{expansion}&unique=prints"